#!/usr/bin/env sh
pnpm lint
npx --no-install commitlint --edit
prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
git update-index --again
. "$(dirname "$0")/_/h"
